@startuml ArticleTrack Use Case
left to right direction

actor "Автор" as Author
actor "Редактор" as Editor

rectangle "Система учёта статей в журнале" {

    usecase "Войти в систему" as UC_Login

    usecase "Подать статью" as UC_SubmitArticle
    usecase "Проверить статус статьи" as UC_CheckStatus

    usecase "Принять/отклонить статью" as UC_Decide
    usecase "Формировать отчёты и статистику" as UC_Reports
    usecase "Управлять рубриками и выпусками" as UC_ManageRubrics
}

Author -- UC_Login
Author -- UC_SubmitArticle
Author -- UC_CheckStatus

Editor -- UC_Login
Editor -- UC_Decide
Editor -- UC_Reports
Editor -- UC_ManageRubrics

@enduml
